version: '2.1'

services:

  nats:
    container_name: nats
    image: nats
    ports:
      - 4200:4222
    networks:
      files:

  minio:
    container_name: minio
    image: minio/minio:latest
    command: server /data
    volumes:
      - minio:/data
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minioadmin
    networks:
      files:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 10s
      retries: 3

  postgres:
    networks:
        - postgres-network
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432

    #docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' para saber o ip do container

  pgadmin4:
    networks:
        - postgres-network
    image: dpage/pgadmin4
    depends_on:
        - postgres
    ports:
      - "300:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=mymail@mail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    links:
      - "postgres:database"

networks:
  postgres-network:
       driver: bridge
  files:

volumes:
  minio:
